### ISSUE TITLE
Tokenizer error "list index out of range" during mapping extension

### ISSUE THREAD

**Issue by Danysan1** [KRR-Oxford/DeepOnto#10]
**Describe the bug**
Under some circumstances dureing the mapping extensions stage the tokenizer throws the error `IndexError: list index out of range`.
The error originates at [bert_classifier.py line 185](https://github.com/KRR-Oxford/DeepOnto/blob/11d7d0d/src/deeponto/align/bertmap/bert_classifier.py#L185).
This is the same error and same location inside the tokenizer of https://github.com/huggingface/tokenizers/issues/993 , which was caused by the data passed to the tokenizer.

**To Reproduce**
I have reproduced this error with these settings:

| Logs & stack trace | `max_length_for_input` | `batch_size_for_training` | Source ontology | Target ontology |
|----|----|----|----|----|
| [link](https://gist.github.com/Danysan1/3c00c66b3cbdf8f73864873315fab0ab#file-bertmap_match_16-ipynb) | 256 | 16 | [music-representation.owl](https://github.com/Danysan1/unibo-ke-matching-ontologies/blob/f5b1e3bb67810e9bf8b79a45ec068d8b240f6116/polifonia/ontology/music-representation.owl) | [musicClasses.owl @ 2ebb641](https://github.com/Danysan1/unibo-ke-matching-ontologies/blob/f5b1e3bb67810e9bf8b79a45ec068d8b240f6116/wikidata/musicClasses.owl) |
| [link](https://gist.github.com/Danysan1/3c00c66b3cbdf8f73864873315fab0ab#file-bertmap_match_8-ipynb) | 128 | 8 | [core.owl](https://github.com/Danysan1/unibo-ke-matching-ontologies/blob/f5b1e3bb67810e9bf8b79a45ec068d8b240f6116/polifonia/ontology/core.owl) | [musicClasses.owl @ ebc2d09](https://github.com/Danysan1/unibo-ke-matching-ontologies/blob/ebc2d09651e4013b858438c5260288699499bc84/wikidata/musicClasses.owl) |

**Expected behavior**
The stage and the pipeline should complete successfully

**Platform:**
 - OS: python notebook on Google Colab
 - Python 3.10
 - Transformers 4.30.2
 - DeepOnto 0.8.3

**Comment by Lawhy** [comment]
Hi @Danysan1, thanks for reporting this. Before I conduct a thorough check, may I ask if every class of your ontologies has at least one label available? I suspect this issue is caused by an empty list of class names. 

Also, the default BERTMap configuration might not include necessary annotation properties available in your ontologies.

**Comment by Danysan1** [comment]
Yes, there were some classes without label. I have fixed them and the pipeline completed succesfully.

It would be ideal to check if this error is present and printing a clear and explicit error before calling the tokenizer.

Similarly, an unclear error is thrown in [text_semantics.py line 232](https://github.com/KRR-Oxford/DeepOnto/blob/v0.8.3/src/deeponto/align/bertmap/text_semantics.py#L232) if the passed ontology has no subClassOf relationships. It would be ideal to receive an explicit error.

**Comment by Lawhy** [comment]
Sure, I will update this in the next release. Thanks for your feedback.
