### ISSUE TITLE
REST API with Dockerfile

### ISSUE THREAD

**Issue by Minitour** [KRR-Oxford/DeepOnto#12]
In addition to a library, consider also creating a Dockerfile which uses FastAPI to serve web APIs that can be used. For instance, instead of having to import the library, I can deploy a docker container and call the APIs for which I will provide all the necessary inputs.

**Comment by Lawhy** [comment]
Thanks for the suggestion and the pointer to FastAPI. We will consider this possibility.

**Comment by Lawhy** [comment]
Docker feature not currently planned.
