### ISSUE TITLE
Small typo in the documentation.

### ISSUE THREAD

**Issue by alkidbaci** [KRR-Oxford/DeepOnto#15]
While exploring the documentation I just came across a small typo in the example code snippets. There is a quotation mark missing in the a line of code there (see the link below). Nothing concerning but I just wanted to let you know. It may cause some unexpected error for those who copy-paste the code :)

`onto.get_subsumption_axioms(entity_type="Classes)` --> `onto.get_subsumption_axioms(entity_type="Classes")` 

https://krr-oxford.github.io/DeepOnto/verbaliser/#:~:text=(entity_type%3D-,%22Classes),-%23%20verbalise%20the%20first

**Comment by Lawhy** [comment]
Many thanks for pointing out typos, I am fixing it right now.
