### ISSUE TITLE
Consistency checking

### ISSUE THREAD

**Issue by Demirrr** [KRR-Oxford/DeepOnto#16]
Dear all,

thank you for DeepOnto.

I was wondering whether there is an example code for consistency checking, e.g.

```python
from deeponto.onto import Ontology
onto = Ontology("path_to_ontology.owl", "hermit")
assert onto.consistent()
```

**Comment by Lawhy** [comment]
Hi @Demirrr, for checking the consistency of an ontology, you can use `onto.reasoner.owl_reasoner.isConsistent()` for now. `owl_reasoner` is an instance of [`OWLReasoner`](https://owlcs.github.io/owlapi/apidocs_4/org/semanticweb/owlapi/reasoner/OWLReasoner.html) in the OWLAPI. 

But I will make a `check_consistency()` method to encapsulate this feature latter.

**Comment by Demirrr** [comment]
Cheers!

**Comment by Lawhy** [comment]
Add feature at [4940b23](https://github.com/KRR-Oxford/DeepOnto/commit/4940b327bd9602863f877d81453a0d1ffce3d810).
