### ISSUE TITLE
installation: cannot import java related packages

### ISSUE THREAD

**Issue by cmdoret** [KRR-Oxford/DeepOnto#20]
**Describe the bug**
After following the installation instructions (via conda) of deeponto+pytorch+jpype, I cannot import the `Ontology` class. It seems that all `org.*` packages cannot be imported.
Setting and exporting `JAVA_HOME` manually does not seem to fix the issue. 

It fails with the following error (full traceback below):

```
ModuleNotFoundError: No module named 'org.slf4j'
```
Any advice would be appreciated.

> NOTICE: I am not familiar with the combination of python x java

**To Reproduce**
1. `conda create -n deeponto python=3.10`
2. `conda activate deeponto`
3. `conda install pytorch torchvision torchaudio cpuonly -c pytorch -c conda-forge`
4. `conda install -c conda-forge jpype1`
6. in python, type `from deeponto.onto import Ontology`

**Expected behavior**
The `Ontology` is imported.

**Screenshots**
Traceback below:
```python
➜ ipython
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.24.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from deeponto.onto import Ontology
Please enter the maximum memory located to JVM [8g]:

INFO:deeponto:8g maximum memory allocated to JVM.
INFO:deeponto:JVM started successfully.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from deeponto.onto import Ontology

File ~/.local/share/micromamba/envs/deeponto/lib/python3.10/site-packages/deeponto/onto/__init__.py:14
      1 # Copyright 2021 Yuan He. All rights reserved.
      2
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from .ontology import Ontology, OntologyReasoner
     15 from .pruning import OntologyPruner
     16 from .verbalisation import OntologyVerbaliser, OntologySyntaxParser

File ~/.local/share/micromamba/envs/deeponto/lib/python3.10/site-packages/deeponto/onto/ontology.py:47
     45 from java.io import File  # type: ignore
     46 from java.lang import Runtime, System  # type: ignore
---> 47 from org.slf4j.impl import SimpleLogger  # type: ignore
     48 System.setProperty(SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "warn")  # set slf4j default logging level to warning
     49 from org.semanticweb.owlapi.apibinding import OWLManager  # type: ignore

ModuleNotFoundError: No module named 'org.slf4j'
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by Lawhy** [comment]
Hi @cmdoret, it is possible to use Python 3.8 or 3.9 for `deeponto`, because it might be an issue with `jpype`. Also, `jpype` should be shipped when installing `deeponto` through `pip`. I am not sure if  the conda version of `jpype` can work here.

**Comment by cmdoret** [comment]
Thanks @Lawhy, I tried recreating the conda environment from scratch using to python 3.8 (also tried with 3.9), the `pip install deeponto` command indeed says:

```
Successfully installed JPype1-1.5.0  [...] deeponto-0.9.1 [...]
```
Yet, I still run into the same issue :/

```py
In [1]: from deeponto.onto import Ontology
Please enter the maximum memory located to JVM [8g]:

INFO:deeponto:8g maximum memory allocated to JVM.
INFO:deeponto:JVM started successfully.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from deeponto.onto import Ontology

File ~/.local/share/micromamba/envs/deeponto38/lib/python3.8/site-packages/deeponto/onto/__init__.py:14
      1 # Copyright 2021 Yuan He. All rights reserved.
      2
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 14 from .ontology import Ontology, OntologyReasoner
     15 from .pruning import OntologyPruner
     16 from .verbalisation import OntologyVerbaliser, OntologySyntaxParser

File ~/.local/share/micromamba/envs/deeponto38/lib/python3.8/site-packages/deeponto/onto/ontology.py:47
     45 from java.io import File  # type: ignore
     46 from java.lang import Runtime, System  # type: ignore
---> 47 from org.slf4j.impl import SimpleLogger  # type: ignore
     48 System.setProperty(SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "warn")  # set slf4j default logging level to warning
     49 from org.semanticweb.owlapi.apibinding import OWLManager  # type: ignore

ModuleNotFoundError: No module named 'org.slf4j'
```
Do you have any other suggestion?

[deeponto_py38_pip.txt](https://github.com/KRR-Oxford/DeepOnto/files/15455697/deeponto_py38_pip.txt)

**Comment by Lawhy** [comment]
It can also be the version of your Java that causes the problem. DeepOnto is using OWL API 4 which requires Java 7 or 8 as the backend.

**Comment by cmdoret** [comment]
Thanks @Lawhy, I tried commenting out that line, but the same error is then raised by the `from org.semanticweb.owlapi.apibinding import OWLManager` statement below, which led me to think it was a JPype problem.

Unfortunately, I cannot afford to downgrade java (11) on my machine, this dependency would make a strong case for dockerizing deeponto and its dependencies. Did you start / plan anything in that direction?

**Comment by Lawhy** [comment]
Hi @cmdoret, have you also tried to test `jpype` alone? It has some default Java imports to play with. Also, please ensure that there is nothing named `org` in your paths or Python dependencies, which will override the Java's modules. This happened once before when another person asked me for help.

About dockers, it is a good idea but I currently have no time to implement this.

**Comment by Thrameos** [comment]
Did you try the statement?

```
print(jpype.java.lang.System.getProperty('java.class.path'))
```

If the jar is in the path and the import statement is failing then it may be a conflicting python module.   This can be bypassed by placing an alias statement such that some other symbol like "jorg" is used to refer to "org".   

Example:
```
import jpype
import jpype.imports
jpype.imports.registerDomain('mypkg','java')  # Someone has foolishly created a "java" directory so we can't import without a conflict
jpype.startJVM()
from mypkg.lang import String  # Imports java.lang.String
```

**Comment by cmdoret** [comment]
@Thrameos thank you, your example worked and help me figure out that the issue was elsewhere :+1:
