### ISSUE TITLE
BERTMapPipeline crashes on custom ontologies 

### ISSUE THREAD

**Issue by cmdoret** [KRR-Oxford/DeepOnto#21]
**Describe the bug**
When attempting to use `BERTMapPipeline` on publicly available ontologies, it fails with the following error:

```
ValueError: evaluation strategy steps requires either non-zero --eval_steps or --logging_steps

```

Based on #18 , I understand that this means deeponto failed to generate training data, however both ontologies are pretty large and have `rdfs:label` annotations. Any advice welcome

**To Reproduce**
1. Download schema.org ontology (or owl variant) on https://schema.org/docs/developers.html
2. Download sphn schema on https://www.biomedit.ch/rdf/sphn-schema/sphn
3. Get default configuration file based on [docs](https://krr-oxford.github.io/DeepOnto/bertmap/#configuration)
4. Run the example from [usage page](https://krr-oxford.github.io/DeepOnto/bertmap/#usage).

```python
from deeponto.onto import Ontology
from deeponto.align.bertmap import BERTMapPipeline

config = BERTMapPipeline.load_bertmap_config('config.yaml')
schemaorg = Ontology('schemaorg.ttl')
sphn = Ontology('sphn_schema.ttl')
BERTMapPipeline(schemaorg, sphn, config)
```

**Expected behavior**
A mapping is generated

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by Lawhy** [comment]
You can try to use `build_annotation_index` or `get_annotations` method to see what happened and if there are any labels generated.

**Comment by Lawhy** [comment]
I also see that sphn with a bunch of imports. I am not sure the OWL API features implemented here can handle those external imports for now. So you can check if the ontologies are really loaded in completely. If not, you can probably use Protege to load and save a complete ontology before using BERTMap.

**Comment by Lawhy** [comment]
Closed as not active.
