### ISSUE TITLE
Please fix the version of transformer library

### ISSUE THREAD

**Issue by magiclogy-** [KRR-Oxford/DeepOnto#3]
I have tried to run BERTMap, but got the following error:

`
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper__index_select)
`

In fact, it is a bug that was introduced in Transformer 4.12.3 and has been fixed in 4.13.0. For short, the output of Tokenizer is `BatchEncoding`, but the Trainer only transfers `Union[torch.Tensor, Tuple, List, Dictionary]` to GPU.
(Please refer to this link for more details [When running the Trainer cell, it found two devices (cuda:0 and CPU)](https://github.com/nlp-with-transformers/notebooks/issues/31))

I think this bug is introduced in this commit [086a25cae945d496765cbbb09b36f9780d676ac7](https://github.com/KRR-Oxford/DeepOnto/commit/086a25cae945d496765cbbb09b36f9780d676ac7). Please consider fixing the version of Transformer.

**Comment by Lawhy** [comment]
Hi @magiclogy-, many thanks for the report, I have now updated the version (to the most recent) of `transformers` in `requirements.txt`.  I have tested with the script `scripts/bertmap.py` and it worked fine on my side.
